---
databases:
  'fever':
    'user': 'fever'
    'password': 'TuvQuassiaj0'
    'host': '%'
  'mint':
    'user': 'mint'
    'password': 'DugpomAjdas2'
    'host': '%'

service:
  'mariadb-server':
    'command': '/usr/sbin/mysqld'
