---

databases:
  'fever':
    'user': 'fever'
    'password': 'IgzearronIf7'
    'host': '%'
  'mint':
    'user': 'mint'
    'password': 'cipht4fravEt'
    'host': '%'

service:
  'mariadb-server':
    'command': '/usr/sbin/mysqld'
